<template>
  <q-page class='my-page basic-form'>
    <div class='row items-center justify-between'>
      <div class='my-page-header'>
        <q-breadcrumbs align='left'>
          <q-breadcrumbs-el
            label='首页'
            to='/'
          />
          <q-breadcrumbs-el label='字体图标' />
        </q-breadcrumbs>
        <div class='row q-col-gutter-md'>
          <div>
            <div class='my-page-header-subtitle'>图标列表</div>
            <div class='q-mt-sm'>内置图标一览，图标选择功能场景。</div>
          </div>
          <q-space />
          <div class='row wrap content-end'>
          </div>
        </div>
      </div>
    </div>
    <div class='my-page-body'>
      <q-form class='my-form gutter'>
        <q-card
          flat
          class='fit'
        >
          <q-card-section v-if="iconSelected">
            <q-btn
              color="primary"
              :icon="iconSelected"
              :label="iconSelected"
            />
          </q-card-section>
          <q-separator />
          <q-card-section class="row column">
            <div class="col q-gutter-sm">
              <q-btn
                flat
                v-for="icon in data.materialIcons.list"
                :key="icon.name"
                :icon="icon.name"
                :color="`${(iconSelected && iconSelected===icon.name) ? 'primary' : null}`"
                @click="onCopyToClipboard(icon.name)"
              />
            </div>

          </q-card-section>
        </q-card>
      </q-form>
    </div>
  </q-page>
</template>

<script>
const materialIcons = {
  name: 'material-icons',
  list: [
    // { name: '360', tags: ['arrow', 'map'] },
    // { name: '3d_rotation', tags: ['web', 'editor'] },
    // { name: '4k', tags: ['media'] },
    { name: 'ac_unit', tags: ['weather', 'map', 'nature'] },
    { name: 'access_alarm', tags: ['accessibility', 'calendar', 'technology'] },
    { name: 'access_alarms', tags: ['accessibility', 'calendar', 'technology'] },
    { name: 'access_time', tags: ['accessibility', 'calendar', 'technology'] },
    { name: 'accessibility', tags: ['accessibility', 'health', 'people'] },
    { name: 'accessibility_new', tags: ['accessibility', 'health', 'people'] },
    // { name: 'accessible', tags: ['accessibility', 'health', 'people'] },
    // { name: 'accessible_forward', tags: ['accessibility', 'health', 'people'] },
    // { name: 'account_balance', tags: ['money'] },
    { name: 'account_balance_wallet', tags: ['money'] },
    { name: 'account_box', tags: ['money', 'people'] },
    { name: 'account_circle', tags: ['money', 'people'] },
    { name: 'adb', tags: ['brand'] },
    { name: 'add', tags: ['editor', 'calendar'] },
    { name: 'add_a_photo', tags: ['editor', 'media'] },
    { name: 'add_alarm', tags: ['editor', 'calendar', 'technology'] },
    { name: 'add_alert', tags: ['editor', 'calendar'] },
    { name: 'add_box', tags: ['editor'] },
    { name: 'add_circle', tags: ['editor', 'calendar'] },
    { name: 'add_circle_outline', tags: ['editor', 'calendar'] },
    { name: 'add_comment', tags: ['editor'] },
    { name: 'add_location', tags: ['editor'] },
    { name: 'add_shopping_cart', tags: ['editor', 'money'] },
    { name: 'add_to_home_screen', tags: ['arrow', 'editor', 'health', 'web'] },
    { name: 'add_to_photos', tags: ['web'] },
    { name: 'add_to_queue', tags: ['media'] },
    { name: 'adjust', tags: ['media'] },
    // { name: 'airline_seat_flat', tags: ['travel', 'people'] },
    // { name: 'airline_seat_flat_angled', tags: ['travel', 'people'] },
    // { name: 'airline_seat_individual_suite', tags: ['travel', 'people'] },
    // { name: 'airline_seat_legroom_extra', tags: ['travel', 'people'] },
    // { name: 'airline_seat_legroom_normal', tags: ['travel', 'people'] },
    // { name: 'airline_seat_legroom_reduced', tags: ['travel', 'people'] },
    // { name: 'airline_seat_recline_extra', tags: ['travel', 'people'] },
    // { name: 'airline_seat_recline_normal', tags: ['travel', 'people'] },
    { name: 'airplanemode_active', tags: ['travel', 'technology', 'web'] },
    { name: 'airplanemode_inactive', tags: ['travel', 'technology', 'web'] },
    // { name: 'airplay', tags: ['arrow', 'media', 'technology'] },
    { name: 'airport_shuttle', tags: ['travel'] },
    { name: 'alarm', tags: ['calendar'] },
    { name: 'alarm_add', tags: ['calendar'] },
    { name: 'alarm_off', tags: ['calendar'] },
    { name: 'alarm_on', tags: ['calendar'] },
    { name: 'album', tags: ['media'] },
    { name: 'all_inbox', tags: ['web'] },
    { name: 'all_inclusive', tags: ['travel'] },
    { name: 'all_out', tags: ['other'] },
    // { name: 'android', tags: ['brand'] },
    // { name: 'announcement', tags: ['web'] },
    { name: 'apps', tags: ['web', 'other'] },
    { name: 'archive', tags: ['arrow', 'calendar'] },
    { name: 'arrow_back', tags: ['arrow'] },
    { name: 'arrow_back_ios', tags: ['arrow'] },
    { name: 'arrow_downward', tags: ['arrow'] },
    { name: 'arrow_drop_down', tags: ['arrow'] },
    { name: 'arrow_drop_down_circle', tags: ['arrow'] },
    { name: 'arrow_drop_up', tags: ['arrow'] },
    { name: 'arrow_forward', tags: ['arrow'] },
    { name: 'arrow_forward_ios', tags: ['arrow'] },
    { name: 'arrow_left', tags: ['arrow'] },
    { name: 'arrow_right', tags: ['arrow'] },
    { name: 'arrow_upward', tags: ['arrow'] },
    { name: 'art_track', tags: ['media'] },
    { name: 'aspect_ratio', tags: ['media'] },
    { name: 'assessment', tags: ['other'] },
    { name: 'assignment', tags: ['other'] },
    { name: 'assignment_ind', tags: ['people', 'other'] },
    { name: 'assignment_late', tags: ['other'] },
    { name: 'assignment_return', tags: ['arrow', 'other'] },
    { name: 'assignment_returned', tags: ['arrow', 'other'] },
    { name: 'assignment_turned_in', tags: ['other'] },
    { name: 'assistant', tags: ['media'] },
    { name: 'assistant_photo', tags: ['media'] },
    // { name: 'atm', tags: ['map', 'money'] },
    // { name: 'attach_file', tags: ['editor'] },
    // { name: 'attach_money', tags: ['editor'] },
    // { name: 'attachment', tags: ['calendar', 'file'] },
    // { name: 'audiotrack', tags: ['media'] },
    // { name: 'autorenew', tags: ['arrow'] },
    // { name: 'av_timer', tags: ['media'] },
    { name: 'backspace', tags: ['arrow'] },
    { name: 'backup', tags: ['editor', 'web'] },
    { name: 'bar_chart', tags: ['editor'] },
    { name: 'bathtub', tags: ['travel', 'people'] },
    // { name: 'battery_alert', tags: ['technology'] },
    // { name: 'battery_charging_full', tags: ['technology'] },
    // { name: 'battery_full', tags: ['technology'] },
    // { name: 'battery_std', tags: ['technology'] },
    // { name: 'battery_unknown', tags: ['technology'] },
    { name: 'beach_access' },
    { name: 'beenhere', tags: ['map'] },
    { name: 'block' },
    { name: 'bluetooth', tags: ['brand', 'technology'] },
    { name: 'bluetooth_audio', tags: ['technology'] },
    { name: 'bluetooth_connected', tags: ['technology'] },
    { name: 'bluetooth_disabled', tags: ['technology'] },
    { name: 'bluetooth_searching', tags: ['technology'] },
    { name: 'blur_circular' },
    { name: 'blur_linear' },
    { name: 'blur_off' },
    { name: 'blur_on' },
    // { name: 'book' },
    // { name: 'bookmark' },
    // { name: 'bookmark_border' },
    // { name: 'border_all', tags: ['editor'] },
    // { name: 'border_bottom', tags: ['editor'] },
    { name: 'border_clear', tags: ['editor'] },
    // { name: 'border_color', tags: ['editor'] },
    // { name: 'border_horizontal', tags: ['editor'] },
    // { name: 'border_inner', tags: ['editor'] },
    // { name: 'border_left', tags: ['editor'] },
    { name: 'border_outer', tags: ['editor'] },
    // { name: 'border_right', tags: ['editor'] },
    // { name: 'border_style', tags: ['editor'] },
    // { name: 'border_top', tags: ['editor'] },
    // { name: 'border_vertical', tags: ['editor'] },
    { name: 'branding_watermark', tags: ['media'] },
    { name: 'brightness_1', tags: ['weather'] },
    { name: 'brightness_2', tags: ['weather'] },
    { name: 'brightness_3', tags: ['weather'] },
    { name: 'brightness_4', tags: ['weather'] },
    { name: 'brightness_5', tags: ['weather'] },
    { name: 'brightness_6', tags: ['weather'] },
    { name: 'brightness_7', tags: ['weather'] },
    { name: 'brightness_auto', tags: ['technology'] },
    { name: 'brightness_high', tags: ['weather', 'technology'] },
    { name: 'brightness_low', tags: ['weather', 'technology'] },
    { name: 'brightness_medium', tags: ['technology'] },
    { name: 'broken_image', tags: ['web', 'media'] },
    { name: 'brush', tags: ['editor'] },
    { name: 'bubble_chart', tags: ['editor'] },
    { name: 'bug_report', tags: ['nature'] },
    { name: 'build' },
    { name: 'burst_mode' },
    // { name: 'business' },
    // { name: 'business_center' },
    { name: 'cached' },
    { name: 'cake', tags: ['calendar'] },
    // { name: 'call' },
    // { name: 'call_end' },
    // { name: 'call_made', tags: ['arrow'] },
    // { name: 'call_merge', tags: ['arrow'] },
    // { name: 'call_missed', tags: ['arrow'] },
    // { name: 'call_missed_outgoing', tags: ['arrow'] },
    // { name: 'call_received', tags: ['arrow'] },
    // { name: 'call_split', tags: ['arrow'] },
    // { name: 'call_to_action', tags: ['media'] },
    { name: 'camera' },
    { name: 'camera_alt' },
    { name: 'camera_enhance' },
    { name: 'camera_front' },
    { name: 'camera_rear' },
    { name: 'camera_roll' },
    { name: 'cancel' },
    { name: 'card_giftcard', tags: ['money'] },
    { name: 'card_membership', tags: ['money'] },
    { name: 'card_travel', tags: ['travel', 'money'] },
    { name: 'casino' },
    { name: 'cast', tags: ['technology'] },
    { name: 'cast_connected', tags: ['technology'] },
    { name: 'category', tags: ['map'] },
    { name: 'center_focus_strong' },
    { name: 'center_focus_weak' },
    { name: 'change_history' },
    { name: 'chat' },
    { name: 'chat_bubble' },
    { name: 'chat_bubble_outline' },
    { name: 'check' },
    { name: 'check_box' },
    { name: 'check_box_outline_blank' },
    { name: 'check_circle' },
    { name: 'chevron_left', tags: ['arrow'] },
    { name: 'chevron_right', tags: ['arrow'] },
    { name: 'child_care', tags: ['people'] },
    { name: 'child_friendly', tags: ['travel'] },
    { name: 'chrome_reader_mode' },
    { name: 'class' },
    { name: 'clear', tags: ['calendar'] },
    { name: 'clear_all' },
    { name: 'close' },
    { name: 'closed_caption', tags: ['media'] },
    { name: 'cloud', tags: ['file', 'weather'] },
    { name: 'cloud_circle', tags: ['file', 'weather'] },
    { name: 'cloud_done', tags: ['file'] },
    { name: 'cloud_download', tags: ['arrow', 'file'] },
    { name: 'cloud_off', tags: ['file'] },
    { name: 'cloud_queue', tags: ['file', 'weather'] },
    { name: 'cloud_upload', tags: ['arrow', 'file'] },
    { name: 'code', tags: ['arrow'] },
    { name: 'collections' },
    { name: 'collections_bookmark' },
    { name: 'color_lens' },
    { name: 'colorize' },
    { name: 'comment', tags: ['calendar'] },
    { name: 'commute', tags: ['travel'] },
    { name: 'compare' },
    { name: 'compare_arrows', tags: ['arrow'] },
    { name: 'compass_calibration', tags: ['map'] },
    { name: 'computer', tags: ['technology'] },
    { name: 'confirmation_number', tags: ['travel'] },
    { name: 'contact_mail' },
    { name: 'contact_phone' },
    // { name: 'contacts' },
    // { name: 'content_copy' },
    // { name: 'content_cut' },
    { name: 'content_paste' },
    { name: 'control_camera', tags: ['arrow', 'media'] },
    { name: 'control_point' },
    // { name: 'control_point_duplicate' },
    { name: 'copyright' },
    { name: 'create' },
    { name: 'create_new_folder', tags: ['file'] },
    { name: 'credit_card' },
    { name: 'crop' },
    { name: 'crop_16_9' },
    { name: 'crop_3_2' },
    { name: 'crop_5_4' },
    { name: 'crop_7_5' },
    { name: 'crop_din' },
    { name: 'crop_free' },
    { name: 'crop_landscape' },
    { name: 'crop_original' },
    { name: 'crop_portrait' },
    { name: 'crop_rotate', tags: ['arrow'] },
    { name: 'crop_square' },
    { name: 'dashboard' },
    { name: 'data_usage', tags: ['technology'] },
    { name: 'date_range' },
    { name: 'deck', tags: ['travel'] },
    { name: 'dehaze' },
    { name: 'delete' },
    { name: 'delete_forever' },
    { name: 'delete_sweep' },
    { name: 'departure_board', tags: ['travel', 'map'] },
    { name: 'description' },
    { name: 'desktop_mac', tags: ['technology'] },
    { name: 'desktop_windows', tags: ['technology'] },
    { name: 'details' },
    { name: 'developer_board', tags: ['technology'] },
    { name: 'developer_mode', tags: ['arrow', 'technology'] },
    { name: 'device_hub', tags: ['technology'] },
    { name: 'device_unknown', tags: ['technology'] },
    { name: 'devices', tags: ['technology'] },
    { name: 'devices_other', tags: ['technology'] },
    { name: 'dialer_sip' },
    { name: 'dialpad' },
    { name: 'directions', tags: ['arrow', 'travel', 'map'] },
    { name: 'directions_bike', tags: ['travel', 'map', 'people'] },
    { name: 'directions_boat', tags: ['travel', 'map'] },
    { name: 'directions_bus', tags: ['travel', 'map'] },
    { name: 'directions_car', tags: ['travel', 'map'] },
    { name: 'directions_railway', tags: ['travel', 'map'] },
    { name: 'directions_run', tags: ['map', 'people'] },
    { name: 'directions_subway', tags: ['travel', 'map'] },
    { name: 'directions_transit', tags: ['travel', 'map'] },
    { name: 'directions_walk', tags: ['map', 'people'] },
    { name: 'disc_full' },
    { name: 'dns' },
    { name: 'do_not_disturb' },
    { name: 'do_not_disturb_alt' },
    { name: 'do_not_disturb_off' },
    { name: 'do_not_disturb_on' },
    { name: 'dock', tags: ['technology'] },
    { name: 'domain', tags: ['web'] },
    { name: 'done' },
    { name: 'done_all' },
    { name: 'donut_large' },
    { name: 'donut_small' },
    { name: 'double_arrow', tags: ['arrow'] },
    { name: 'drafts' },
    { name: 'drag_handle', tags: ['editor'] },
    { name: 'drive_eta', tags: ['travel'] },
    { name: 'dvr', tags: ['technology'] },
    { name: 'edit', tags: ['editor'] },
    { name: 'edit_attributes', tags: ['map'] },
    { name: 'edit_location' },
    { name: 'eject' },
    { name: 'eco', tags: ['nature'] },
    { name: 'email' },
    { name: 'emoji_emotions' },
    { name: 'emoji_events', tags: ['sport'] },
    { name: 'emoji_flags', tags: ['sport'] },
    { name: 'emoji_food_beverage', tags: ['food'] },
    { name: 'emoji_nature', tags: ['nature'] },
    { name: 'emoji_objects' },
    { name: 'emoji_people', tags: ['people'] },
    { name: 'emoji_symbols' },
    { name: 'emoji_transportation' },
    { name: 'enhanced_encryption' },
    { name: 'equalizer', tags: ['media'] },
    { name: 'error', tags: ['calendar'] },
    { name: 'error_outline', tags: ['calendar'] },
    { name: 'euro_symbol' },
    { name: 'ev_station', tags: ['map'] },
    { name: 'event', tags: ['calendar'] },
    { name: 'event_available' },
    { name: 'event_busy' },
    { name: 'event_note' },
    { name: 'event_seat' },
    { name: 'exit_to_app' },
    { name: 'expand_less', tags: ['arrow'] },
    { name: 'expand_more', tags: ['arrow'] },
    { name: 'explicit', tags: ['media'] },
    { name: 'explore' },
    { name: 'exposure' },
    // { name: 'exposure_neg_1' },
    // { name: 'exposure_neg_2' },
    // { name: 'exposure_plus_1' },
    // { name: 'exposure_plus_2' },
    // { name: 'exposure_zero' },
    { name: 'extension' },
    { name: 'face', tags: ['people'] },
    { name: 'fastfood', tags: ['food', 'map'] },
    { name: 'fast_forward', tags: ['arrow', 'media'] },
    { name: 'fast_rewind', tags: ['arrow', 'media'] },
    { name: 'favorite' },
    { name: 'favorite_border' },
    { name: 'featured_play_list', tags: ['media'] },
    { name: 'featured_video', tags: ['media'] },
    { name: 'feedback' },
    { name: 'fiber_dvr', tags: ['media'] },
    { name: 'fiber_manual_record', tags: ['media'] },
    { name: 'fiber_new', tags: ['media'] },
    { name: 'fiber_pin', tags: ['media'] },
    { name: 'fiber_smart_record', tags: ['media'] },
    { name: 'file_copy', tags: ['file'] },
    { name: 'file_download', tags: ['file'] },
    { name: 'file_upload', tags: ['file'] },
    // { name: 'filter' },
    // { name: 'filter_1' },
    // { name: 'filter_2' },
    // { name: 'filter_3' },
    // { name: 'filter_4' },
    // { name: 'filter_5' },
    // { name: 'filter_6' },
    // { name: 'filter_7' },
    // { name: 'filter_8' },
    // { name: 'filter_9' },
    // { name: 'filter_9_plus' },
    { name: 'filter_b_and_w' },
    { name: 'filter_center_focus' },
    { name: 'filter_drama' },
    { name: 'filter_frames' },
    { name: 'filter_hdr', tags: ['nature'] },
    { name: 'filter_list' },
    { name: 'filter_none' },
    { name: 'filter_tilt_shift' },
    { name: 'filter_vintage' },
    { name: 'find_in_page' },
    { name: 'find_replace' },
    { name: 'fingerprint' },
    { name: 'fireplace', tags: ['travel'] },
    { name: 'first_page', tags: ['arrow'] },
    { name: 'fitness_center' },
    { name: 'flag', tags: ['travel', 'calendar'] },
    { name: 'flare' },
    // { name: 'flash_auto' },
    // { name: 'flash_off' },
    // { name: 'flash_on' },
    { name: 'flight', tags: ['travel', 'map'] },
    { name: 'flight_land', tags: ['travel', 'map'] },
    { name: 'flight_takeoff', tags: ['travel', 'map'] },
    { name: 'flip' },
    { name: 'flip_to_back' },
    { name: 'flip_to_front' },
    { name: 'folder', tags: ['file'] },
    { name: 'folder_open', tags: ['file'] },
    { name: 'folder_shared', tags: ['file'] },
    { name: 'folder_special', tags: ['file'] },
    { name: 'font_download' },
    { name: 'format_align_center', tags: ['editor'] },
    { name: 'format_align_justify', tags: ['editor'] },
    { name: 'format_align_left', tags: ['editor'] },
    { name: 'format_align_right', tags: ['editor'] },
    { name: 'format_bold', tags: ['editor'] },
    { name: 'format_clear', tags: ['editor'] },
    { name: 'format_color_fill', tags: ['editor'] },
    { name: 'format_color_reset', tags: ['editor'] },
    { name: 'format_color_text', tags: ['editor'] },
    { name: 'format_indent_decrease', tags: ['arrow', 'editor'] },
    { name: 'format_indent_increase', tags: ['arrow', 'editor'] },
    // { name: 'format_italic', tags: ['editor'] },
    // { name: 'format_line_spacing', tags: ['arrow', 'editor'] },
    // { name: 'format_list_bulleted', tags: ['editor'] },
    // { name: 'format_list_numbered', tags: ['editor'] },
    { name: 'format_paint', tags: ['editor'] },
    // { name: 'format_quote', tags: ['editor'] },
    { name: 'format_shapes', tags: ['editor'] },
    // { name: 'format_size', tags: ['editor'] },
    // { name: 'format_strikethrough', tags: ['editor'] },
    // { name: 'format_textdirection_l_to_r', tags: ['arrow', 'editor'] },
    // { name: 'format_textdirection_r_to_l', tags: ['arrow', 'editor'] },
    // { name: 'format_underlined', tags: ['editor'] },
    { name: 'forum' },
    { name: 'forward', tags: ['arrow', 'media'] },
    { name: 'forward_10', tags: ['arrow', 'media'] },
    { name: 'forward_30', tags: ['arrow', 'media'] },
    { name: 'forward_5', tags: ['arrow', 'media'] },
    { name: 'free_breakfast', tags: ['food'] },
    { name: 'fullscreen' },
    { name: 'fullscreen_exit' },
    { name: 'functions', tags: ['editor'] },
    { name: 'g_translate' },
    { name: 'gamepad', tags: ['technology'] },
    { name: 'games', tags: ['media'] },
    { name: 'gavel', tags: ['other'] },
    { name: 'gesture', tags: ['technology'] },
    { name: 'get_app' },
    { name: 'gif', tags: ['web'] },
    { name: 'golf_course', tags: ['sport'] },
    { name: 'gps_fixed', tags: ['technology'] },
    { name: 'gps_not_fixed', tags: ['technology'] },
    { name: 'gps_off', tags: ['technology'] },
    { name: 'grade' },
    { name: 'gradient', tags: ['media', 'web'] },
    { name: 'grain' },
    { name: 'graphic_eq' },
    // { name: 'grid_off', tags: ['web'] },
    { name: 'grid_on', tags: ['web'] },
    { name: 'group', tags: ['people'] },
    { name: 'group_add', tags: ['people'] },
    { name: 'group_work', tags: ['other'] },
    { name: 'hd', tags: ['media'] },
    { name: 'hdr_off' },
    { name: 'hdr_on' },
    { name: 'hdr_strong' },
    { name: 'hdr_weak' },
    { name: 'headset', tags: ['technology'] },
    { name: 'headset_mic', tags: ['technology'] },
    { name: 'healing' },
    { name: 'hearing', tags: ['accessibility', 'media'] },
    { name: 'height', tags: ['arrow', 'editor'] },
    { name: 'help' },
    { name: 'help_outline' },
    { name: 'high_quality', tags: ['media'] },
    { name: 'highlight', tags: ['editor'] },
    { name: 'highlight_off', tags: ['editor'] },
    { name: 'history', tags: ['arrow'] },
    { name: 'home' },
    { name: 'hot_tub', tags: ['travel', 'people'] },
    { name: 'hotel', tags: ['travel', 'map'] },
    { name: 'hourglass_empty' },
    { name: 'hourglass_full' },
    { name: 'how_to_reg', tags: ['people'] },
    { name: 'http' },
    { name: 'https' },
    { name: 'image' },
    { name: 'image_aspect_ratio' },
    { name: 'import_contacts' },
    { name: 'import_export', tags: ['arrow'] },
    { name: 'important_devices' },
    { name: 'inbox' },
    { name: 'indeterminate_check_box' },
    { name: 'info' },
    { name: 'info_outline' },
    { name: 'input', tags: ['arrow'] },
    { name: 'insert_chart', tags: ['editor'] },
    { name: 'insert_chart_outlined', tags: ['editor'] },
    { name: 'insert_comment', tags: ['editor'] },
    { name: 'insert_drive_file', tags: ['editor'] },
    { name: 'insert_emoticon', tags: ['editor'] },
    { name: 'insert_invitation', tags: ['calendar', 'editor'] },
    { name: 'insert_link', tags: ['calendar', 'editor'] },
    { name: 'insert_photo', tags: ['calendar', 'editor'] },
    { name: 'invert_colors' },
    { name: 'invert_colors_off' },
    { name: 'iso' },
    { name: 'keyboard', tags: ['technology'] },
    { name: 'keyboard_arrow_down', tags: ['arrow', 'technology'] },
    { name: 'keyboard_arrow_left', tags: ['arrow', 'technology'] },
    { name: 'keyboard_arrow_right', tags: ['arrow', 'technology'] },
    { name: 'keyboard_arrow_up', tags: ['arrow', 'technology'] },
    { name: 'keyboard_backspace', tags: ['arrow', 'technology'] },
    { name: 'keyboard_capslock', tags: ['arrow', 'technology'] },
    { name: 'keyboard_hide', tags: ['arrow', 'technology'] },
    { name: 'keyboard_return', tags: ['arrow', 'technology'] },
    { name: 'keyboard_tab', tags: ['arrow', 'technology'] },
    { name: 'keyboard_voice', tags: ['technology'] },
    { name: 'king_bed', tags: ['travel'] },
    { name: 'kitchen' },
    { name: 'label' },
    { name: 'label_outline' },
    { name: 'landscape', tags: ['travel', 'nature'] },
    { name: 'language' },
    { name: 'laptop', tags: ['technology'] },
    { name: 'laptop_chromebook', tags: ['technology'] },
    { name: 'laptop_mac', tags: ['technology'] },
    { name: 'laptop_windows', tags: ['technology'] },
    { name: 'last_page', tags: ['arrow'] },
    { name: 'launch', tags: ['arrow'] },
    { name: 'layers', tags: ['map'] },
    { name: 'layers_clear', tags: ['map'] },
    { name: 'leak_add' },
    { name: 'leak_remove' },
    { name: 'lens' },
    { name: 'library_add', tags: ['media'] },
    { name: 'library_books', tags: ['media'] },
    { name: 'library_music', tags: ['media'] },
    { name: 'lightbulb_outline' },
    { name: 'line_style' },
    { name: 'line_weight' },
    { name: 'linear_scale', tags: ['editor'] },
    { name: 'link' },
    { name: 'linked_camera' },
    { name: 'list' },
    { name: 'live_help' },
    { name: 'live_tv', tags: ['arrow'] },
    { name: 'local_activity', tags: ['map'] },
    { name: 'local_airport', tags: ['travel', 'map'] },
    { name: 'local_atm', tags: ['map', 'money'] },
    { name: 'local_bar', tags: ['map'] },
    { name: 'local_cafe', tags: ['map'] },
    { name: 'local_car_wash', tags: ['map'] },
    { name: 'local_convenience_store', tags: ['map'] },
    { name: 'local_dining', tags: ['travel', 'map'] },
    { name: 'local_drink', tags: ['travel', 'map'] },
    { name: 'local_florist', tags: ['map', 'nature'] },
    { name: 'local_gas_station', tags: ['map'] },
    { name: 'local_grocery_store', tags: ['map'] },
    { name: 'local_hospital', tags: ['health', 'map'] },
    { name: 'local_hotel', tags: ['travel', 'map'] },
    { name: 'local_laundry_service', tags: ['map'] },
    { name: 'local_library', tags: ['map', 'people'] },
    { name: 'local_mall', tags: ['map'] },
    { name: 'local_movies', tags: ['map'] },
    { name: 'local_offer', tags: ['map'] },
    { name: 'local_parking', tags: ['travel', 'map'] },
    { name: 'local_pharmacy', tags: ['map'] },
    { name: 'local_phone', tags: ['map'] },
    { name: 'local_pizza', tags: ['map'] },
    { name: 'local_play', tags: ['map'] },
    { name: 'local_post_office', tags: ['map'] },
    { name: 'local_printshop', tags: ['map'] },
    { name: 'local_see', tags: ['map'] },
    { name: 'local_shipping', tags: ['map'] },
    { name: 'local_taxi', tags: ['travel', 'map'] },
    { name: 'location_city', tags: ['travel'] },
    { name: 'location_disabled' },
    { name: 'location_off' },
    { name: 'location_on' },
    { name: 'location_searching' },
    { name: 'lock' },
    { name: 'lock_open' },
    { name: 'lock_outline' },
    // { name: 'looks' },
    // { name: 'looks_3' },
    // { name: 'looks_4' },
    // { name: 'looks_5' },
    // { name: 'looks_6' },
    // { name: 'looks_one' },
    // { name: 'looks_two' },
    { name: 'loop', tags: ['arrow', 'media'] },
    { name: 'loupe' },
    { name: 'low_priority', tags: ['arrow'] },
    { name: 'loyalty' },
    { name: 'mail' },
    { name: 'mail_outline' },
    { name: 'map', tags: ['travel', 'map'] },
    { name: 'markunread' },
    { name: 'markunread_mailbox' },
    { name: 'memory', tags: ['technology'] },
    { name: 'menu' },
    { name: 'menu_open', tags: ['arrow'] },
    { name: 'merge_type', tags: ['arrow', 'editor'] },
    { name: 'message' },
    { name: 'mic', tags: ['media'] },
    { name: 'mic_none', tags: ['media'] },
    { name: 'mic_off', tags: ['media'] },
    { name: 'missed_video_call', tags: ['media'] },
    { name: 'mms' },
    { name: 'mobile_friendly', tags: ['technology'] },
    { name: 'mobile_off', tags: ['technology'] },
    { name: 'mode_comment', tags: ['editor'] },
    { name: 'mode_edit' },
    { name: 'monetization_on', tags: ['editor'] },
    { name: 'money', tags: ['money'] },
    { name: 'money_off', tags: ['editor'] },
    { name: 'monochrome_photos' },
    { name: 'mood' },
    { name: 'mood_bad' },
    { name: 'more', tags: ['calendar'] },
    { name: 'more_horiz' },
    { name: 'more_vert' },
    { name: 'motorcycle', tags: ['travel'] },
    { name: 'mouse', tags: ['technology'] },
    { name: 'move_to_inbox', tags: ['arrow'] },
    { name: 'movie', tags: ['media'] },
    { name: 'movie_creation' },
    { name: 'movie_filter' },
    { name: 'multiline_chart', tags: ['editor'] },
    { name: 'music_note' },
    { name: 'music_video', tags: ['media'] },
    { name: 'my_location', tags: ['map'] },
    { name: 'nature', tags: ['nature'] },
    { name: 'nature_people', tags: ['people', 'nature'] },
    { name: 'navigate_before', tags: ['arrow'] },
    { name: 'navigate_next', tags: ['arrow'] },
    { name: 'navigation', tags: ['arrow', 'map'] },
    { name: 'near_me', tags: ['arrow', 'map'] },
    { name: 'network_cell' },
    { name: 'network_check', tags: ['arrow'] },
    { name: 'network_locked' },
    { name: 'network_wifi' },
    { name: 'new_releases', tags: ['media'] },
    { name: 'next_week', tags: ['arrow', 'calendar'] },
    { name: 'nfc' },
    { name: 'nights_stay', tags: ['travel'] },
    { name: 'no_encryption' },
    { name: 'no_sim' },
    { name: 'not_interested', tags: ['media'] },
    { name: 'note', tags: ['media'] },
    { name: 'notes', tags: ['editor'] },
    { name: 'note_add' },
    { name: 'notification_important', tags: ['calendar'] },
    { name: 'notifications', tags: ['calendar'] },
    { name: 'notifications_active', tags: ['calendar'] },
    { name: 'notifications_none', tags: ['calendar'] },
    { name: 'notifications_off', tags: ['calendar'] },
    { name: 'notifications_paused', tags: ['calendar'] },
    { name: 'offline_pin' },
    { name: 'ondemand_video' },
    { name: 'opacity' },
    { name: 'open_in_browser', tags: ['arrow'] },
    { name: 'open_in_new', tags: ['arrow'] },
    { name: 'open_with' },
    { name: 'pages' },
    { name: 'pageview' },
    { name: 'palette' },
    // { name: 'pan_tool' },
    // { name: 'panorama' },
    { name: 'panorama_fish_eye' },
    // { name: 'panorama_horizontal' },
    // { name: 'panorama_vertical' },
    // { name: 'panorama_wide_angle' },
    // { name: 'party_mode' },
    // { name: 'pause', tags: ['media'] },
    { name: 'pause_circle_filled', tags: ['media'] },
    { name: 'pause_circle_outline', tags: ['media'] },
    { name: 'payment' },
    { name: 'people', tags: ['people'] },
    { name: 'people_alt', tags: ['people'] },
    { name: 'people_outline', tags: ['people'] },
    { name: 'perm_camera_mic' },
    { name: 'perm_contact_calendar', tags: ['calendar', 'people'] },
    { name: 'perm_data_setting' },
    { name: 'perm_device_information' },
    { name: 'perm_identity', tags: ['people'] },
    // { name: 'perm_media' },
    { name: 'perm_phone_msg' },
    { name: 'perm_scan_wifi' },
    { name: 'person', tags: ['people'] },
    { name: 'person_add', tags: ['people'] },
    { name: 'person_outline', tags: ['people'] },
    { name: 'person_pin', tags: ['map'] },
    { name: 'person_pin_circle' },
    { name: 'personal_video' },
    { name: 'pets', tags: ['nature', 'health'] },
    { name: 'phone', tags: ['technology'] },
    { name: 'phone_android', tags: ['technology'] },
    { name: 'phone_bluetooth_speaker', tags: ['technology'] },
    { name: 'phone_callback', tags: ['arrow', 'technology'] },
    { name: 'phone_forwarded', tags: ['arrow', 'technology'] },
    { name: 'phone_in_talk', tags: ['technology'] },
    { name: 'phone_iphone', tags: ['technology'] },
    { name: 'phone_locked', tags: ['technology'] },
    { name: 'phone_missed', tags: ['arrow', 'technology'] },
    { name: 'phone_paused', tags: ['technology'] },
    { name: 'phonelink', tags: ['technology'] },
    { name: 'phonelink_erase', tags: ['technology'] },
    { name: 'phonelink_lock', tags: ['technology'] },
    { name: 'phonelink_off', tags: ['technology'] },
    { name: 'phonelink_ring', tags: ['technology'] },
    { name: 'phonelink_setup', tags: ['technology'] },
    { name: 'photo' },
    { name: 'photo_album' },
    { name: 'photo_camera' },
    { name: 'photo_filter' },
    { name: 'photo_library', tags: ['travel'] },
    { name: 'photo_size_select_actual', tags: ['travel'] },
    { name: 'photo_size_select_large' },
    { name: 'photo_size_select_small' },
    { name: 'picture_as_pdf' },
    { name: 'picture_in_picture' },
    { name: 'picture_in_picture_alt' },
    { name: 'pie_chart', tags: ['editor'] },
    { name: 'pie_chart_outlined', tags: ['editor'] },
    { name: 'pin_drop' },
    { name: 'place' },
    { name: 'play_arrow', tags: ['arrow', 'media'] },
    { name: 'play_circle_filled', tags: ['arrow', 'media'] },
    { name: 'play_circle_outline', tags: ['arrow', 'media'] },
    { name: 'play_for_work', tags: ['arrow'] },
    { name: 'playlist_add', tags: ['media'] },
    { name: 'playlist_add_check', tags: ['media'] },
    { name: 'playlist_play', tags: ['arrow', 'media'] },
    { name: 'plus_one' },
    { name: 'poll' },
    { name: 'polymer' },
    { name: 'pool', tags: ['travel', 'people'] },
    { name: 'portable_wifi_off' },
    { name: 'portrait', tags: ['travel'] },
    { name: 'post_add', tags: ['calendar', 'editor'] },
    { name: 'power' },
    { name: 'power_input', tags: ['technology'] },
    { name: 'power_settings_new' },
    { name: 'pregnant_woman', tags: ['health', 'people'] },
    { name: 'present_to_all', tags: ['arrow'] },
    { name: 'print' },
    { name: 'priority_high' },
    { name: 'public', tags: ['travel'] },
    { name: 'publish', tags: ['arrow', 'calendar', 'editor'] },
    { name: 'query_builder' },
    { name: 'question_answer' },
    { name: 'queue', tags: ['media'] },
    { name: 'queue_music', tags: ['media'] },
    { name: 'queue_play_next', tags: ['arrow', 'media'] },
    { name: 'radio', tags: ['media'] },
    { name: 'radio_button_checked' },
    { name: 'radio_button_unchecked' },
    { name: 'rate_review', tags: ['map'] },
    { name: 'receipt' },
    { name: 'recent_actors', tags: ['media'] },
    { name: 'record_voice_over', tags: ['media', 'people'] },
    { name: 'redeem' },
    { name: 'redo', tags: ['arrow', 'calendar'] },
    { name: 'refresh', tags: ['arrow', 'calendar'] },
    { name: 'remove', tags: ['calendar'] },
    { name: 'remove_circle', tags: ['calendar'] },
    { name: 'remove_circle_outline', tags: ['calendar'] },
    { name: 'remove_from_queue', tags: ['media'] },
    { name: 'remove_red_eye' },
    { name: 'remove_shopping_cart' },
    { name: 'reorder' },
    { name: 'repeat', tags: ['arrow', 'media'] },
    { name: 'repeat_one', tags: ['arrow', 'media'] },
    { name: 'replay', tags: ['arrow', 'media'] },
    { name: 'replay_10', tags: ['arrow', 'media'] },
    { name: 'replay_30', tags: ['arrow', 'media'] },
    { name: 'replay_5', tags: ['arrow', 'media'] },
    { name: 'reply', tags: ['arrow'] },
    { name: 'reply_all', tags: ['arrow'] },
    { name: 'report' },
    { name: 'report_problem' },
    { name: 'restaurant', tags: ['travel', 'map'] },
    { name: 'restaurant_menu', tags: ['travel', 'map'] },
    { name: 'restore' },
    { name: 'restore_page' },
    { name: 'ring_volume' },
    { name: 'room' },
    { name: 'room_service', tags: ['travel'] },
    { name: 'rotate_90_degrees_ccw', tags: ['arrow'] },
    { name: 'rotate_left', tags: ['arrow'] },
    { name: 'rotate_right', tags: ['arrow'] },
    { name: 'rounded_corner' },
    { name: 'router', tags: ['technology'] },
    { name: 'rowing', tags: ['sport', 'travel', 'health', 'people'] },
    { name: 'rss_feed' },
    { name: 'rv_hookup', tags: ['arrow', 'travel'] },
    { name: 'satellite', tags: ['map'] },
    { name: 'save', tags: ['file'] },
    { name: 'save_alt', tags: ['arrow', 'file'] },
    { name: 'scanner', tags: ['technology'] },
    { name: 'scatter_plot', tags: ['editor'] },
    { name: 'schedule', tags: ['calendar'] },
    { name: 'school' },
    { name: 'score', tags: ['editor'] },
    { name: 'screen_lock_landscape' },
    { name: 'screen_lock_portrait' },
    { name: 'screen_lock_rotation' },
    { name: 'screen_rotation' },
    { name: 'screen_share', tags: ['arrow'] },
    { name: 'sd_card' },
    { name: 'sd_storage' },
    { name: 'search' },
    { name: 'security', tags: ['technology'] },
    { name: 'select_all' },
    { name: 'send', tags: ['arrow'] },
    { name: 'sentiment_dissatisfied', tags: ['people'] },
    { name: 'sentiment_neutral', tags: ['people'] },
    { name: 'sentiment_satisfied', tags: ['people'] },
    { name: 'sentiment_very_dissatisfied', tags: ['people'] },
    { name: 'sentiment_very_satisfied', tags: ['people'] },
    { name: 'settings' },
    { name: 'settings_applications' },
    { name: 'settings_backup_restore', tags: ['arrow'] },
    { name: 'settings_bluetooth' },
    { name: 'settings_brightness' },
    { name: 'settings_cell' },
    { name: 'settings_ethernet', tags: ['arrow'] },
    { name: 'settings_input_antenna' },
    { name: 'settings_input_component' },
    { name: 'settings_input_composite' },
    { name: 'settings_input_hdmi' },
    { name: 'settings_input_svideo' },
    { name: 'settings_overscan' },
    { name: 'settings_phone' },
    { name: 'settings_power' },
    { name: 'settings_remote' },
    { name: 'settings_system_daydream' },
    { name: 'settings_voice' },
    { name: 'share' },
    { name: 'shop', tags: ['arrow'] },
    { name: 'shop_two', tags: ['arrow'] },
    { name: 'shopping_basket' },
    { name: 'shopping_cart' },
    { name: 'short_text', tags: ['editor'] },
    { name: 'show_chart', tags: ['editor'] },
    { name: 'shuffle', tags: ['arrow', 'media'] },
    // { name: 'signal_cellular_4_bar' },
    // { name: 'signal_cellular_connected_no_internet_4_bar' },
    // { name: 'signal_cellular_no_sim' },
    // { name: 'signal_cellular_null' },
    // { name: 'signal_cellular_off' },
    // { name: 'signal_wifi_4_bar' },
    // { name: 'signal_wifi_4_bar_lock' },
    // { name: 'signal_wifi_off' },
    { name: 'sim_card', tags: ['technology'] },
    { name: 'sim_card_alert' },
    { name: 'single_bed', tags: ['travel'] },
    { name: 'skip_next', tags: ['arrow', 'media'] },
    { name: 'skip_previous', tags: ['arrow', 'media'] },
    { name: 'slideshow' },
    { name: 'slow_motion_video', tags: ['arrow', 'media'] },
    { name: 'smartphone', tags: ['technology'] },
    { name: 'smoke_free', tags: ['travel'] },
    { name: 'smoking_rooms', tags: ['travel'] },
    { name: 'sms' },
    { name: 'sms_failed' },
    { name: 'snooze', tags: ['media'] },
    { name: 'sort' },
    { name: 'sort_by_alpha', tags: ['arrow', 'media'] },
    { name: 'spa' },
    { name: 'space_bar', tags: ['editor'] },
    { name: 'speaker', tags: ['technology'] },
    { name: 'speaker_group', tags: ['technology'] },
    { name: 'speaker_notes' },
    { name: 'speaker_notes_off' },
    { name: 'speaker_phone', tags: ['technology'] },
    { name: 'speed', tags: ['arrow', 'media'] },
    { name: 'spellcheck' },
    { name: 'sports', tags: ['sport'] },
    { name: 'sports_baseball', tags: ['sport'] },
    { name: 'sports_basketball', tags: ['sport'] },
    { name: 'sports_cricket', tags: ['sport'] },
    { name: 'sports_esports', tags: ['sport'] },
    { name: 'sports_football', tags: ['sport'] },
    { name: 'sports_golf', tags: ['sport'] },
    { name: 'sports_handball', tags: ['sport', 'people'] },
    { name: 'sports_hockey', tags: ['sport'] },
    { name: 'sports_kabaddi', tags: ['sport', 'people'] },
    { name: 'sports_mma', tags: ['sport'] },
    { name: 'sports_motorsports', tags: ['sport'] },
    { name: 'sports_rugby', tags: ['sport'] },
    { name: 'sports_soccer', tags: ['sport'] },
    { name: 'sports_tennis', tags: ['sport'] },
    { name: 'sports_volleyball', tags: ['sport'] },
    { name: 'star' },
    { name: 'star_border' },
    { name: 'star_half' },
    { name: 'stars' },
    { name: 'stay_current_landscape' },
    { name: 'stay_current_portrait' },
    { name: 'stay_primary_landscape' },
    { name: 'stay_primary_portrait' },
    { name: 'stop', tags: ['media'] },
    { name: 'stop_screen_share', tags: ['arrow'] },
    { name: 'storage' },
    { name: 'store' },
    { name: 'store_mall_directory', tags: ['map'] },
    { name: 'straighten' },
    { name: 'streetview', tags: ['map'] },
    { name: 'strikethrough_s', tags: ['editor'] },
    { name: 'style' },
    { name: 'subdirectory_arrow_left', tags: ['arrow'] },
    { name: 'subdirectory_arrow_right', tags: ['arrow'] },
    { name: 'subject' },
    { name: 'subscriptions', tags: ['arrow', 'media'] },
    { name: 'subtitles', tags: ['media'] },
    { name: 'subway', tags: ['travel', 'map'] },
    { name: 'supervised_user_circle', tags: ['people'] },
    { name: 'supervisor_account', tags: ['people'] },
    { name: 'surround_sound', tags: ['media'] },
    { name: 'swap_calls', tags: ['arrow'] },
    { name: 'swap_horiz', tags: ['arrow'] },
    { name: 'swap_vert', tags: ['arrow'] },
    { name: 'swap_vertical_circle', tags: ['arrow'] },
    { name: 'switch_camera' },
    { name: 'switch_video' },
    { name: 'sync' },
    { name: 'sync_alt', tags: ['arrow'] },
    { name: 'sync_disabled' },
    { name: 'sync_problem' },
    { name: 'system_update', tags: ['arrow'] },
    { name: 'system_update_alt', tags: ['arrow'] },
    { name: 'tab' },
    { name: 'tab_unselected' },
    { name: 'table_chart', tags: ['editor'] },
    { name: 'tablet', tags: ['technology'] },
    { name: 'tablet_android', tags: ['technology'] },
    { name: 'tablet_mac', tags: ['technology'] },
    { name: 'tag_faces' },
    // { name: 'tap_and_play' },
    // { name: 'terrain', tags: ['map', 'nature'] },
    // { name: 'text_fields', tags: ['editor'] },
    // { name: 'text_format' },
    // { name: 'text_rotate_up', tags: ['arrow'] },
    // { name: 'text_rotate_vertical', tags: ['arrow'] },
    // { name: 'text_rotation_angledown', tags: ['arrow'] },
    // { name: 'text_rotation_angleup', tags: ['arrow'] },
    // { name: 'text_rotation_down', tags: ['arrow'] },
    // { name: 'text_rotation_none', tags: ['arrow'] },
    { name: 'textsms' },
    { name: 'texture' },
    { name: 'theaters' },
    { name: 'thumb_down' },
    { name: 'thumb_up' },
    { name: 'thumbs_up_down' },
    { name: 'time_to_leave' },
    { name: 'timelapse' },
    { name: 'timeline' },
    { name: 'timer' },
    { name: 'timer_10' },
    { name: 'timer_3' },
    { name: 'timer_off' },
    { name: 'title', tags: ['editor'] },
    { name: 'toc' },
    { name: 'today' },
    { name: 'toll' },
    { name: 'tonality' },
    { name: 'touch_app' },
    { name: 'toys', tags: ['technology'] },
    { name: 'track_changes' },
    { name: 'traffic', tags: ['map'] },
    { name: 'train', tags: ['travel', 'map'] },
    { name: 'tram', tags: ['travel', 'map'] },
    { name: 'transfer_within_a_station', tags: ['arrow', 'map', 'people'] },
    { name: 'transform' },
    { name: 'transit_enterexit', tags: ['arrow', 'map'] },
    { name: 'translate' },
    { name: 'trending_down', tags: ['arrow'] },
    { name: 'trending_flat', tags: ['arrow'] },
    { name: 'trending_up', tags: ['arrow'] },
    { name: 'trip_origin', tags: ['map'] },
    { name: 'tune' },
    { name: 'turned_in' },
    { name: 'turned_in_not' },
    { name: 'tv', tags: ['technology'] },
    { name: 'unarchive', tags: ['calendar', 'file'] },
    { name: 'undo', tags: ['arrow', 'calendar'] },
    { name: 'unfold_less', tags: ['arrow'] },
    { name: 'unfold_more', tags: ['arrow'] },
    { name: 'update' },
    { name: 'usb', tags: ['arrow'] },
    { name: 'verified_user' },
    { name: 'vertical_align_bottom', tags: ['arrow', 'editor'] },
    { name: 'vertical_align_center', tags: ['arrow', 'editor'] },
    { name: 'vertical_align_top', tags: ['arrow', 'editor'] },
    { name: 'vibration' },
    { name: 'video_call', tags: ['media'] },
    { name: 'video_label', tags: ['media'] },
    { name: 'video_library', tags: ['arrow', 'media'] },
    { name: 'videocam', tags: ['media'] },
    { name: 'videocam_off', tags: ['media'] },
    { name: 'videogame_asset', tags: ['technology'] },
    { name: 'view_agenda', tags: ['calendar'] },
    { name: 'view_array' },
    { name: 'view_carousel' },
    { name: 'view_column' },
    { name: 'view_comfy' },
    { name: 'view_compact' },
    { name: 'view_day', tags: ['calendar'] },
    { name: 'view_headline' },
    { name: 'view_list' },
    { name: 'view_module' },
    { name: 'view_quilt' },
    { name: 'view_stream' },
    { name: 'view_week', tags: ['calendar'] },
    { name: 'vignette' },
    { name: 'visibility', tags: ['accessibility', 'health'] },
    { name: 'visibility_off', tags: ['accessibility', 'health'] },
    { name: 'voice_chat' },
    { name: 'voice_over_off', tags: ['accessibility', 'people'] },
    { name: 'voicemail' },
    { name: 'volume_down', tags: ['media'] },
    { name: 'volume_mute', tags: ['media'] },
    { name: 'volume_off', tags: ['media'] },
    { name: 'volume_up', tags: ['media'] },
    { name: 'vpn_key' },
    { name: 'vpn_lock' },
    { name: 'wallpaper' },
    { name: 'warning', tags: ['calendar'] },
    { name: 'watch', tags: ['technology'] },
    { name: 'watch_later', tags: ['calendar'] },
    { name: 'wb_auto' },
    { name: 'wb_cloudy', tags: ['weather'] },
    { name: 'wb_incandescent' },
    { name: 'wb_iridescent' },
    { name: 'wb_sunny' },
    { name: 'wc', tags: ['people'] },
    { name: 'web', tags: ['media'] },
    { name: 'web_asset', tags: ['media'] },
    { name: 'weekend' },
    { name: 'whatshot' },
    { name: 'widgets' },
    { name: 'wifi' },
    { name: 'wifi_lock' },
    { name: 'wifi_tethering' },
    { name: 'work', tags: ['health'] },
    { name: 'work_off', tags: ['health'] },
    { name: 'work_outline', tags: ['health'] },
    { name: 'wrap_text', tags: ['arrow', 'editor'] },
    { name: 'youtube_searched_for' },
    { name: 'zoom_in', tags: ['accessibility'] },
    { name: 'zoom_out', tags: ['accessibility'] },
    { name: 'zoom_out_map', tags: ['accessibility', 'arrow', 'map'] }
  ]
}
import { copyToClipboard } from 'quasar'
export default {
  name: 'FontImage',
  meta: { title: '字体图标' },
  data () {
    return {
      loading: false,
      data: {
        materialIcons: {}
      },
      iconSelected: null
    }
  },
  created () {
  },
  mounted () {
    this.data.materialIcons = materialIcons
  },
  methods: {
    onCopyToClipboard (value) {
      this.iconSelected = value
      copyToClipboard(value)
        .then(() => {
          // success!
          this.$q.notify({ type: 'positive', position: 'top', icon: value, message: value })
        })
        .catch(() => {
          // fail
        })
    }
  }
}
</script>

<style lang='sass' scoped>
</style>
